In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,8,9,7],np.int8)

In [3]:
myarr

array([3, 6, 8, 9, 7], dtype=int8)

In [4]:
myarr1=np.array([[3,6,8,9,7]],np.int8)

In [5]:
myarr1[0,1]

6

In [6]:
myarr1.shape

(1, 5)

In [7]:
myarr1.dtype

dtype('int8')

In [8]:
myarr1[0,1]=45

In [9]:
myarr1[0,1]

45

In [10]:
myarr1.size

5

In [11]:
zeros=np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.shape

(2, 5)

In [14]:
range=np.arange(0,15)

In [15]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
range1=np.arange(10)

In [17]:
range1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
lspace=np.linspace(1,12,10)

In [19]:
lspace

array([ 1.        ,  2.22222222,  3.44444444,  4.66666667,  5.88888889,
        7.11111111,  8.33333333,  9.55555556, 10.77777778, 12.        ])

In [20]:
emptyarr=np.empty((5,5))

In [21]:
emptyarr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.00398212e-307, 4.00524160e-307],
       [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
        1.11261095e-306, 3.56043054e-307],
       [1.37961641e-306, 2.22518251e-306, 1.33511969e-306,
        6.23037657e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
        6.23061763e-307, 8.90104239e-307],
       [6.89804132e-307, 1.20160711e-306, 1.42410974e-306,
        5.97819431e-322, 3.91792476e-317]])

In [22]:
identity=np.identity(20)

In [23]:
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [24]:
identity.shape

(20, 20)

In [25]:
identity.dtype

dtype('float64')

In [26]:
arr=np.arange(45)

In [27]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [28]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

**reshape is used to chage the dimension of arr and ravel() is used for changing it into 1 d matrix

In [33]:
x=[[1,2,3],[5,6,7],[4,5,9]]

In [34]:
ar=np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 9]])

In [36]:
ar.sum(axis=0)

array([10, 13, 19])

In [37]:
ar.sum(axis=1)

array([ 6, 18, 18])

In [38]:
ar.T

array([[1, 5, 4],
       [2, 6, 5],
       [3, 7, 9]])

**ar.Ti is used for tranpose

In [39]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
5
6
7
4
5
9


In [43]:
ar.ndim

2

**ndim is used for finding dimension of arr

In [44]:
ar.nbytes

36

In [45]:
one =np.array([1,2,3,445,3,456,78])

In [46]:
one.argmax()

5

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 1, 2, 4, 6, 3, 5], dtype=int64)

In [50]:
ar.argmax(axis=0)

array([1, 1, 2], dtype=int64)

In [51]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 9]])

In [52]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [55]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [4],
       [5],
       [9]])

In [56]:
ar.ravel


<function ndarray.ravel>

In [57]:
ar.ravel()

array([1, 2, 3, 5, 6, 7, 4, 5, 9])

In [58]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 9]])

In [60]:
ar2=np.array([[1,4,5],[6,9,8],[4,7,2]])

In [61]:
ar2

array([[1, 4, 5],
       [6, 9, 8],
       [4, 7, 2]])

In [62]:
ar+ar2

array([[ 2,  6,  8],
       [11, 15, 15],
       [ 8, 12, 11]])

In [63]:
ar*ar2

array([[ 1,  8, 15],
       [30, 54, 56],
       [16, 35, 18]])

In [65]:
np.sqrt(ar2)

array([[1.        , 2.        , 2.23606798],
       [2.44948974, 3.        , 2.82842712],
       [2.        , 2.64575131, 1.41421356]])

In [66]:
ar.sum()

42

In [67]:
ar.max()

9

In [68]:
ar.min()

1

In [70]:
np.where(ar2>5)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 1], dtype=int64))

In [71]:
ar2

array([[1, 4, 5],
       [6, 9, 8],
       [4, 7, 2]])

In [72]:
np.where(ar2>8)

(array([1], dtype=int64), array([1], dtype=int64))

In [73]:
np.where(ar2>7)

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [74]:
np.count_nonzero(ar)

9

In [77]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [80]:
np.tolist()

AttributeError: module 'numpy' has no attribute 'tolist'